# ===============================
# PUERTO (RENDER)
# ===============================
server.port=${PORT:8080}


# ===============================
# BASE DE DATOS (H2 TEMPORAL)
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# ===============================
# H2 CONSOLE (DEBUG)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ===============================
# SPRING
# ===============================
spring.main.web-application-type=servlet


# ===============================
# LOGGING (OPCIONAL)
# ===============================
logging.level.root=INFO

# ===============================
# MAIL (DESACTIVADO TEMPORAL)
# ===============================
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=${MAIL_USERNAME}
# spring.mail.password=${MAIL_PASSWORD}
#
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true
